name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 11 Pro Max']

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
          xcodebuild clean build -project Test_CICD.xcodeproj -scheme Test_CICD -destination "${destination}"
      env:
         destination: ${{ matrix.destination }}
    - name: Run tests
      run: swift test -v
